[package]
name = "keylogger"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.28", features = ["derive"] }
env_logger = "0.11.6"
serde = { version = "1.0.217", features = ["derive"] }
